name: Node.js CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: ['18.20.3']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: ./path-to-subdirectory
    - run: |
        touch .env
        echo "${{ secrets.Dev_ENV }}" > .env
      working-directory: ./path-to-subdirectory
